# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Run updateYaml script
      run: npm run update-yaml
    - name: Check if YAML changed (Linux)
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        git diff --quiet rule-template/cuevox.yaml || echo "yaml_changed=true" >> $GITHUB_ENV
    - name: Check if YAML changed (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      continue-on-error: true
      run: |
        git diff --quiet rule-template/cuevox.yaml
        if ($LASTEXITCODE -ne 0) {
          echo "yaml_changed=true" >> $env:GITHUB_ENV
        }
    - name: Emit warning if YAML changed
      if: env.yaml_changed == 'true'
      run: |
        echo "::warning file=rule-template/cuevox.yaml::Check Rule Template YAML, it might contain different scripts."